game:
  devModeShortcuts: false
  languages: ['en', 'de']
  maxActiveQuests: 4
  canSwitchQuests: false
  duration: 540
town:
  width: 6265
  height: 1080
textures:
  bundles:
    - name: 'town-view'
      assets:
        - name: 'town-bg'
          srcs: 'quantum-city.jpg'
        - name: 'town-collmap'
          srcs: 'quantum-city-collmap.jpg'
        - name: 'player-1'
          srcs: 'player-1.json'
        - name: 'player-2'
          srcs: 'player-2.json'
        - name: 'player-3'
          srcs: 'player-3.json'
        - name: 'npcs-demo'
          srcs: 'npcs-demo.json'
        - name: 'mood-balloon'
          srcs: 'mood-balloon.json'
        - name: 'map-markers'
          srcs: 'map-markers.json'
        - name: 'icons'
          srcs: 'icons.json'
        - name: 'target-arrow'
          srcs: 'target-arrow.png'
        - name: 'guide-arrow'
          srcs: 'guide-arrow.png'
        - name: 'bank-grass-left'
          srcs: 'bank-grass-left.png'
        - name: 'bank-grass-right'
          srcs: 'bank-grass-right.png'
        - name: 'cafe-bag'
          srcs: 'cafe-bag.png'
        - name: 'cafe-counter'
          srcs: 'cafe-counter.png'
        - name: 'cafe-table-01'
          srcs: 'cafe-table-01.png'
        - name: 'cafe-table-02'
          srcs: 'cafe-table-02.png'
        - name: 'forest-big-mushrooms'
          srcs: 'forest-big-mushrooms.png'
        - name: 'forest-medium-mushrooms'
          srcs: 'forest-medium-mushrooms.png'
        - name: 'forest-small-mushrooms-1'
          srcs: 'forest-small-mushrooms-1.png'
        - name: 'forest-small-mushrooms-2'
          srcs: 'forest-small-mushrooms-2.png'
        - name: 'forest-tiny-mushroom'
          srcs: 'forest-tiny-mushroom.png'
        - name: 'post-office'
          srcs: 'post-office.png'
players:
  1:
    color: '#27a6a8'
    spawn: { x: 2500, y: 750 }
storylines:
  - lovedataweek
i18n:
  ui:
    title:
      en: 'Quantum Quest'
    pressStart:
      en: "Press to start"
    decisionMade:
      en: 'Thank you for playing! Here are your quest achievements:'
      de: 'Danke fürs Spielen! Hier sind deine Quest-Ergebnisse:'
    waitingToBegin:
      en: 'Get ready! A new game will begin soon.'
    waitingToEnd:
      en: 'Waiting for the other players…'
    pressToContinue:
      en: 'Press to continue'
    defaultPrompt:
      en: 'Interact with people in this future world and complete quests to learn how quantum computing works.'
      de: 'Interagiere mit Menschen in dieser zukünftigen Welt und löse Aufgaben, um zu lernen, wie Quantencomputing funktioniert.'
    includedInDecision:
      en: 'Included in the decision'
    inclusionBarTitle:
      en: 'Who decides?'



